---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: airflow-monitoring
  namespace: team_name
spec:
  schedule: "5 12 * * *"
  timeZone: "Europe/Prague"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: airflow-monitoring
              image: ghcr.io/direct-technologies-cz/airflow-monitoring:sha-faedd0d
              imagePullPolicy: Always
              env:
                - name: PSQL
                  valueFrom:
                    secretKeyRef:
                      name: team_name-secret
                      key: team_name-psql
                - name: AIRFLOW_USER
                  value: "<user>"
                - name: AIRFLOW_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: team_name-secret
                      key: airflow-password
                - name: AIRFLOW_URL
                  value: "<apiUrl>"
                - name: USER_AGENT
                  value: "team_name airflow_monitoring"
                - name: ENVIRONMENT
                  value: "production"
              args: ["poetry", "run", "python", "-m", "airflow_monitoring.main"]

---
